### PR TITLE
Fix chart loading indicator spinning forever

### LINKED ISSUE #1684: chart loading indicator spinning forever
On an address page that has no transaction history.

example https://explorer.dcrdata.org/address/DsQxuVRvS4eaJ42dhQEsCXauMWjvopWgrVg

### PR DESCRIPTION
**Pull request by ademuanthony**
Closes #1684 
 
This PR resolved the issue of chart loading indicator spinning forever on dummy address pages.
image

### CODE REVIEW

File: public/js/controllers/address_controller.js [hunk 1]
```diff
@@ -227,7 +227,8 @@ export default class extends Controller {
 
   bindElements () {
     this.flowBoxes = this.flowTarget.querySelectorAll('input')
-    this.pageSizeOptions = this.pagesizeTarget.querySelectorAll('option')
+    // pagesizeTarget is not available for dummy addresses
+    this.pageSizeOptions = this.data.get('isDummy') === 'false' ? this.pagesizeTarget.querySelectorAll('option') : []
```
Comment (chappjc) [inline public/js/controllers/address_controller.js]: The comment is really what you are after, so I suggest checking for the target directly rather than adding a data element:

```js
this.pageSizeOptions = this.hasPagesizeTarget ? this.pagesizeTarget.querySelectorAll('option') : []
```

https://stimulusjs.org/reference/targets

File: views/address.tmpl [hunk 2]
```diff
@@ -13,6 +13,7 @@
       data-address-dcraddress="{{.Address}}"
       data-address-txn-count="{{$TxnCount}}"
       data-address-balance="{{toFloat64Amount .Balance.TotalUnspent}}"
+      data-address-is-dummy="{{.IsDummyAddress}}"
```
Comment (chappjc) [inline views/address.tmpl]: If `hashPagesizeTarget` works out, can remove this data attribute.
